server:
  port: 8387
# Oracle Connect
spring:

  #File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger
    
  #JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp    
      
  # gmail Transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: rollout147@gmail.com 
    password: bbwt lmdi vhew burk
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true    
      

  # Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml